Copy-Item E:/Code/cpp/DemoProjects/models/1802_pm.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_chair.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1310_shu0.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1705_qt100.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1311_flower.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1310_chuang.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_flag.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1311_tong.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_left_leg_bottom.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1104_laoying01.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1705_zdt.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1405_ch1.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1214_people.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1405_pm.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/0801_pm.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1408_guanyin10.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1506_airship.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1404_ver.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_floor.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1806_konglong.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1402_pm.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1708_plane03.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/0801_qt.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1501_tree.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1704_pm.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1107_zd.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_body.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1506_base.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_right_foot.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_right_leg_bottom.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1707_poolnew.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_left_foot.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1311_woodpile.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_left_top.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1003_zhuotui.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1508_cft.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1003_chuang.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_floor.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1311_skybox.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1708_plane04.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1507_dog.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1702_stone2.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/0909_plane.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1504_mountainPart.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1503_wall.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_desk.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1402_yh.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1405_ptch.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1310_shu1.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_left_leg_top.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1806_test.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1806_ball.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_pillarY.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1802_cft.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1401_car.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1803_SpaceStationL.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1406_pm.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_head.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1305_rect.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1402_ch.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1310_mirror.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1106_head.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_balckboard.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1310_yizi0.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_doorframe.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_pillarW.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1801_qt.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1401_tree.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1104_laoying02.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_right_bottom.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_whiteboard.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1802_qt.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1001_qt.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1708_plane02.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1311_qiao.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_right_leg_top.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_galsshandle.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1802_yh.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1702_qiu.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1503_people.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1104_laoying03.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/0701_ch.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1003_zhuomian.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_glasscover.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1408_pingtai.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/0909_ball.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1310_deng.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1302_ball.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/0801_cft.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/0801_ch.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1503_floor.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/0911_screw.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1311_tree.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1405_ch2.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1001_yh.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1708_plane01.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_right_top.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1702_stone3.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1408_carBody.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/0704_ch_t.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1311_house.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1001_cft.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_glass.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1214_brazier.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1001_plane.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1310_skybox.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1802_ch.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1702_stone.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1402_qt.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1311_mushroom.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_window.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1408_carWheel.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_platform.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1311_fb.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1705_qt.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1306_konglong.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1212_ch.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1601_left_bottom.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1803_SpaceStation.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1402_cft.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1301_ch_t.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1501_tree01.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_roof.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_wall.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1001_ch.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1505_door.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/1311_table.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/0706_ch.obj D:/models中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/models/0801_yh.obj D:/models中文文件名/
