Copy-Item E:/Code/cpp/DemoProjects/textures/1407_tree.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0603_robot0.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1003_zhuomian.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1311_qiao.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1801_snooker3.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0911_red4level.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1405_c2.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1214_brazier.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1505_flag.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1001_yh.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1001_floor.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1104_laoying.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0906_default_c.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0605_mipmap.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0901_desert.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1705_muwen.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1408_sn.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1305_gridnt.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1214_people.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1707_skycubemap_back.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1311_stuff02.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1506_base.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1310_deng.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1504_snow.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1603_nskinbl.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0906_detailTexture_4.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0609_boardRed.bn3dtex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0909_mdbtm.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1801_snooker0.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0906_default_d.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1501_hd1.bnhdt D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1601_wenli.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1710_floor.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0907_skycubemap_up.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0906_detailTexture_3.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1702_stone.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1310_shu1.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1003_sha.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1103_leaf.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1003_zhuotui.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1702_stone2.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1707_skycubemap_down.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1505_blackboard.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1101_vulkan.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0906_detailTexture_1.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0906_default.bnhdt D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1001_box.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1403_floor.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1103_land1.bnhdt D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1504_mountain.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1707_cube.bntexcube D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1103_caodi.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1310_skybox.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1806_rock.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1707_skycubemap_left.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1601_arm.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1301_cube.bntexcube D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0604_32Linear.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1001_ball.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0606_earth.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1307_flare1.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1710_tree.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1214_wall.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1503_brick.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1803_SpaceStation512.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0611_mipmapAnisotropy.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1103_water.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0610_vulkan.bntexa D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1604_b.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0902_grassMipMap.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1404_w.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1503_people.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1505_window.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1307_flare2.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1507_dog.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0607_wall.dds D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1501_tree1.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1702_stone3.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1401_tree.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0907_skycubemap_front.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1801_snooker2.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1103_treetrunk.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1311_tree.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0901_tree.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1707_skycubemap_up.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1806_konglong.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1405_c1.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0903_rock.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1603_Astronaut_Low.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1705_qt.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1505_whiteboard.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1306_konglongn.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1207_object.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0907_skycubemap_down.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1401_car.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0908_sky.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1508_Head_256x256x256.bn3dtex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0909_mdb.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1702_noise2.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1505_chair.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0909_ball.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1207_object1.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1601_head.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1707_skycubemap_right.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0604_256Linear.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1708_plane03.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1801_wall.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1604_a.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1503_floor.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1506_baseBloom.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1214_diban.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1702_noise3.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1311_house.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1102_vulkan.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1803_kjz.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1704_people.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1702_qiu.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1310_mirror.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1505_glass.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1306_konglong.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0801A_lgq.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0907_skycubemap_right.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0907_skycubemap_left.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1505_roof.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1206_tex1.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1501_grass.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1501_tree.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1214_fire.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1508_Head_256x256x256.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1203_pm.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1708_plane04.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1702_noise1.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1707_poolnew.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1310_yizi.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1801_snooker1.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1310_shu0.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0704_ghxp.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1003_chuang.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0906_detailTexture_2.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1311_resultnt.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1707_skycubemap_front.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0609_boardGreen.bn3dtex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1003_dm.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1506_airshipBloom.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1801_snooker6.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0802_cloud.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1305_ghxp.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0905_land.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1506_airship.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1708_plane01.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1706_haimian.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1408_pt.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1307_flare3.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1311_vegetation01.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1106_head.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1801_green_table.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1408_carWheel.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1212_3dNoise.bn3dtex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0911_red8level.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0606_earthn.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1405_pm.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1408_dx1.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1501_sky_cloud.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1107_zd_bg.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1310_chuang.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0801_lgq.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1311_water.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1206_tex2.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1408_carBody.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1801_snooker5.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0902_land.bnhdt D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1801_snooker4.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0606_moon.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0608_fp.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0907_skycubemap_back.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1311_sky.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/0601_wall.bntex D:/textures中文文件名/
Copy-Item E:/Code/cpp/DemoProjects/textures/1103_sand.bntex D:/textures中文文件名/
